### ISSUE TITLE
Configure dataset name at runtime

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [rom-rb/rom-sql#106]
Hello,  I have a usecase where I need to use a relation but the table target might be different,  based on a configuration on application load. Is using `Class. new { dataset myvar }` my only option to set this variable? I tried using Myclass.dataset(myvariable) but didn't change anything. 

Any recommendation? My library is a logger to write stuff on the database and would like to give user the possibility to pick the table every time a new logger is instantiated. Obviously is quite challenging since I need to be able to use a repository which can have different relations as targets.

**Comment by solnic** [comment]
This is an interesting use case. It's possible to instantiate a relation manually by passing a dataset to its constructor. Try experimenting with `YourRelation.new(rom.gateways[:your_gateway_id].dataset(some_dataset_id)`. IIRC it should be possible to instantiate a repo with a hash like `YourRepo.new(hash_with_relations)`.

**Comment by Fire-Dragon-DoL** [comment]
That's extremely helpful, thanks @solnic !

I have an unrelated question but I'll ask here for the sake of it. I'm working with my collegue, Dave, and we are using a good chunk of the gems you created (dry-types, dry-structs, rom-rb, rom-sql and I don't remember what else). We were planning to collect a list of where documentation is lacking to have a better overview and then fill the holes. Where can we open such topic? Should we create an issue here (notice that will be an "ongoing" issue as we build the list), on the dry-types forum, on the rom-rb forums? I would like to initially make just one list because we are touching a lot of parts all at once, we can split it once it's more "stable"

**Comment by solnic** [comment]
@Fire-Dragon-DoL you could start a thread on dry-rb forum, even when it's going to include rom-related stuff, this way more folks could chime in :)

**Comment by Fire-Dragon-DoL** [comment]
@solnic I tried following your suggestion but based on the source code, `ROM::Repository` and `ROM::Repository::Root` both accept only a container as an argument, and by reading the source code, they both look for relations in there.
I've been trying to register the relation (the instance of the relation) right before the repository is returned, but looks like is impossible (without hacking around), because the relation repository is readonly and I can only register relation CLASSES, not relation instances ( I would love to be able to just say `rom.register_relation(:logs, Logs.new(rom))`)

For now I'll force the library to use the `:logs` table because it's taking me already various hours in trial-and-error.

Thanks again for your support, not sure if you want to close the ticket or not

**Comment by solnic** [comment]
> I would love to be able to just say rom.register_relation(:logs, Logs.new(dataset))`

You can do `register_relation(:logs, Class.new(Logs) { dataset :some_ds_identifier })` - would that work for you?

**Comment by Fire-Dragon-DoL** [comment]
Yeah I figured out that's the approach, thanks. I would have preferred passing in the relation as an argument, but I guess it's fine with initializing a class.

**Comment by solnic** [comment]
Hmm, I'm wondering though - maybe your library could simply provide an API for switching datasets? Relations do that all the time whenever you use a query DSL or your own relation view. Internally it's just a matter of doing `logs.__new__(a_different_dataset)` but we can add a public `Relation#new(dataset)` interface. Is your library available on github?

**Comment by Fire-Dragon-DoL** [comment]
Hey @solnic , don't bother with it, didn't want to add work. Unfortunately the library for now it's an internal tool, especially because we have yet to start using it, so if we open source it (which is entirely possible), it's definitely too early since it's not battle tested.

I got it working with your suggestion anyway, it's good enough.
Swapping dataset seems fine, but isn't `__new__` a private API?

**Comment by solnic** [comment]
It is private but it would be better if we had a public api for that (we actually need it in some places in other rom parts).

Cheers
Piotr
