### ISSUE TITLE
[inferrer] Add support for "line" and "circle" PG types

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-sql#141]
Hanami model expects that `line` and `circle` PG types can be automatically inferred, so it would be nice if we could have that supported by PG inferrer.

Here's what Sequel gives us about these types:

``` ruby
# "line"
[:geometric1, {:oid=>600, :db_type=>"point", :default=>nil, :allow_null=>true, :primary_key=>false, :type=>nil, :ruby_default=>nil}]

# circle
[:geometric3, {:oid=>718, :db_type=>"circle", :default=>"'<(15,15),1>'::circle", :allow_null=>true, :primary_key=>false, :type=>nil, :ruby_default=>nil}]
```

Refs hanami/model#370

**Comment by flash-gordon** [comment]
It makes sense to add support for the rest of PG geometric datatypes https://www.postgresql.org/docs/9.6/static/datatype-geometric.html

The whole list would be
- [x] point
- [ ] line
- [ ] circle
- [ ] lseg
- [ ] box
- [ ] path (closed and open)
- [ ] polygon

**Comment by Morozzzko** [comment]
I'll check this out. Probably gonna have something by the end of the week (Feb 04-05)
