### ISSUE TITLE
missing attributes in ROM::Relation::Name for pg timestamp(0)

### ISSUE THREAD

**Issue by jcsjcs** [rom-rb/rom-sql#144]
When connecting to a postgres database with a table containing this column:
~~~sql
created_on timestamp(0) without time zone
~~~
``ROM.container`` raises ``ROM::Schema::MissingAttributesError``.
It seems to choke because of the ``(0)``.

**Comment by flash-gordon** [comment]
Oh, can confirm, thanks for reporting, will fix that

**Comment by flash-gordon** [comment]
@jcsjcs btw you work around this with manual attribute definition:
```ruby
schema(infer: true) do
  attribute :created_on, Types::Time
end
```

**Comment by jcsjcs** [comment]
Thanks @flash-gordon, noted in case I need to work with timestamps.

This is a table I'm not interested in at the moment, so I'm just using the workaround mentioned in #132 to avoid automatically discovering it. The database has 393 tables and I'm only working with a few of them.

**Comment by solnic** [comment]
@jcsjcs you may want to disable table inference if you have so many tables, ie pass `inferrable_relations: []` to your rom config and it won't try to infer all the tables, and only explicitly defined relations will be used.
