### ISSUE TITLE
Reading#fetch result cannot be mapped by rom-repo

### ISSUE THREAD

**Issue by flash-gordon** [rom-rb/rom-sql#150]
```ruby
rom = ROM.container(:sql, 'sqlite::memory') do |config|
  config.default.connection.create_table(:users) do
    primary_key :id
    column :name, String, null: false
  end
end

repo = Class.new(ROM::Repository[:users]) {
  def by_id(id)
    users.fetch(id)
  end
}.new(rom)

user_repo.by_id(1) 
#=> {id: 1, name: 'Malcolm Reynolds'} <= this is a plain Hash
```

Originally `rom` docs were saying it returns `ROM::Struct`, but I have updated them to show the actual output.

The problem is that `#fetch` is defined in `rom-sql` and thus `rom-repo` does not know anything about it. `RelationProxy#fetch` returns a hash, so it cannot be mapped. The most surprising thing here is that if you copy & paste `fetch` definition to your repo, then it's gonna work, compare:
```ruby
repo = Class.new(ROM::Repository[:users]) {
  def by_id(id)
    users.by_pk(id).one!
  end
}.new(rom)

user_repo.by_id(1) 
#=> #<ROM::Struct[User] id=1 name="Malcolm Reynolds"> <= now this is a ROM::Struct!
```

Well, we could have some sort of API for this, so it can be used by `first` and `last` methods too:

```ruby
  def fetch(id)
    r = by_pk(id)
    (block_given? ? yield(r) : r).one!
  end

  def first
    block_given? ? yield([dataset.first]).first : dataset.first
  end
```

This API seems very tricky and fragile to me, but I can't come up with something else atm

@solnic wdyt?

**Comment by solnic** [comment]
Re `fetch` this is really not a method that should be used, I added it specifically for changesets, I don't know why it ended up in docs, we have `one` and `one!` for retrieving a single struct from a relation, that's what should be used.

`first` and `last` are HORRIBLE methods, I hate that people got used to them and expect them to work. Their behavior may not be consistent across adapters, they *should* rely on ordered relation, but not all adapters may be able to guarantee that, and so on.

**Comment by flash-gordon** [comment]
Fair point. I'll update docs with `by_pk(id).one!`. `first` and `last` are not horrible, but I'd say specific. I use `first` quite often in the REPL and never in the application code.

**Comment by flash-gordon** [comment]
Let's keep it close for now, assuming that one day we'll move the proxy relation API from rom-repo to rom-core, then we will able to add an effective `first` implementation at least. But since it's adapter-specific, we probably won't add it anyway.
