### ISSUE TITLE
group method can't handle "old" Sequel fields

### ISSUE THREAD

**Issue by choallin** [rom-rb/rom-sql#162]
I have configured Rom to use the legacy SequelAPI modul and it works for many parts of the application.
But if I want to use a group by clause with the group method I get this error message:

> KeyError: :query_objects__id attribute doesn't exist in query_objects schema

where query_objects is the table and id the field

**Comment by solnic** [comment]
Fixed via https://github.com/rom-rb/rom-sql/commit/bc5c2e5ae1beac3e188b9a3fd78c91ca7b8fb6ae
