### ISSUE TITLE
Some method chains for comparison values in where blocks don't work

### ISSUE THREAD

**Issue by timriley** [rom-rb/rom-sql#170]
In a relation class, I was adding a method to encapsulate querying for records "in the future", but I wanted to anchor the comparison to the beginning of the current day, so that an record at e.g. 8pm doesn't disappear immediately at 8:01pm, but rather at 12:01am the next day (the purpose for this is an "events" calendar for a shop).

I turned to trusty time_math2 to help me with this. My first attempt was this:

```ruby
      def in_future
        where { date_and_time >= TimeMath(Time.now).floor(:day) }
      end
```

But this failed with an error like this:

```
[2] pry(main)> repo.for_shop(1).to_a
NoMethodError: undefined method `floor' for #<Sequel::SQL::Function:0x007fd4a2deea58>
from /Users/tim/src/readings-2016/lib/persistence/relations/events.rb:22:in `block in in_future'

Exception: NoMethodError: undefined method `floor' for #<Sequel::SQL::Function:0x007fd4a8d29d38>
--
0: /Users/tim/src/readings-2016/lib/persistence/relations/events.rb:22:in `block in in_future'
1: /Users/tim/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rom-sql-1.1.1/lib/rom/sql/restriction_dsl.rb:9:in `instance_exec'
2: /Users/tim/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rom-sql-1.1.1/lib/rom/sql/restriction_dsl.rb:9:in `call'
3: /Users/tim/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rom-sql-1.1.1/lib/rom/sql/schema.rb:27:in `restriction'
4: /Users/tim/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rom-sql-1.1.1/lib/rom/sql/relation/reading.rb:341:in `where'
5: /Users/tim/src/readings-2016/lib/persistence/relations/events.rb:22:in `in_future'
6: /Users/tim/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rom-3.1.0/lib/rom/pipeline.rb:66:in `method_missing'
7: /Users/tim/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rom-repository-1.1.0/lib/rom/repository/relation_proxy.rb:297:in `method_missing'
```

This seems to be somehow related to the chaining of methods I was doing here. `ROM::SQL::RestrictionDSL#method_missing` was sending `:TimeMath` to `::Sequel::VIRTUAL_ROW` and getting a `Sequel::SQL::Function` back, which obviously wouldn't respond to TimeMath's API.

If I adjust the query so there's a different kind of chain, it works:

```ruby
      def in_future
        # Broken:
        # where { date_and_time >= TimeMath(Time.now).floor(:day) }

        # Works!
        where { date_and_time >= TimeMath.day.floor(Time.now) }
      end
```

I'm not _really_ sure why this works and the other doesn't. Any ideas? It'd probably be ideal if the DSL could somehow support both kinds of approaches?

**Comment by flash-gordon** [comment]
The first calls TimeMath method and the last resolves TimeMath constant
instead. If you adjust it to TimeMath() it will fail as well

**Comment by solnic** [comment]
DSL is a basic object so you gotta do `::TimeMatch()`

**Comment by timriley** [comment]
Thanks both, will give this a try :)

**Comment by timriley** [comment]
`::TimeMath(Time.now)` is actually a syntax error, it turns out. So you got to do something like this:

```ruby
where { date_and_time >= ::Kernel.send(:TimeMath, Time.now).floor(:day).call }
```

Because TimeMath (the method) is just defined in the global namespace in its lib file.

So at least I know how to do it, anyway 😬 

In this case I don't _need_ to chain multiple TimeMath operations, so I might stick to the cleaner looking version:

```ruby
where { date_and_time >= TimeMath.day.floor(Time.now) }
```

**Comment by solnic** [comment]
we could have a plugin for TimeMath that would expose a nice API inside these blocks. Also, I believe `::Kernel.TimeMath` should work too.

**Comment by solnic** [comment]
btw this will work too: `where(self[:date_and_time] >= TimeMath.floort(:day).())`

**Comment by timriley** [comment]
I thought that would work too, @solnic, but it actually didn't. I got this error:

```
NoMethodError: private method `TimeMath' called for Kernel:Module
```

**Comment by flash-gordon** [comment]
btw `where { created_at >= now }` produces `AND ("created_at" >= NULL)`, will look into it later today
