### ISSUE TITLE
Inner join doesn't work with Repository::RelationProxy

### ISSUE THREAD

**Issue by davydovanton** [rom-rb/rom-sql#172]
Hey, I have an application with rom-repository. In this application, I try to call `#inner_join` method with relation proxy object. For example:

```ruby
repo = PostRepo.new(rom)

repo.posts.qualified
  .join(repo.users)
  .join(repo.comments)
```

And this code raise error:
```
ArgumentError: +other+ must be either a symbol or a relation, ROM::Repository::RelationProxy given
from /Users/anton/.rvm/gems/ruby-2.4.0/gems/rom-sql-1.0.0/lib/rom/sql/relation/reading.rb:802:in `__join__'
```

I told with @flash-gordon about it and he told that the problem in this case statement: https://github.com/rom-rb/rom-sql/blob/master/lib/rom/sql/relation/reading.rb#L820

**Comment by solnic** [comment]
For now just do `repo.users.relation`, this problem will be gone in rom 4.0 as we'll move repo extra features to rom core and `RelationProxy` will be no more, it'll cease to be, it'll be expired and gone to meet its maker.

Alternatively, we may want to add `RelationProxy#===` for now so that it works with case statements, it pretends to be a normal relation after all.

**Comment by flash-gordon** [comment]
@solnic `===` will be called on `Relation`, not on the object we're trying to match, we could go with `other.respond_to?(:name) && other.name.is_a?(Relation::Name)` check, wdyt?

**Comment by solnic** [comment]
@flash-gordon hmm I thought that if we add `def ===(c); super || c === ROM::Relation; end` then it would work, but I'm OK with a respond_to for now, we can remove it in 4.0 :)

**Comment by flash-gordon** [comment]
nope, it works like this
```ruby
$ irb
2.3.3 :001 > a = Object.new
 => #<Object:0x007fd183821598>
2.3.3 :002 > b = Object.new
 => #<Object:0x007fd183830de0>
2.3.3 :003 > def a.===(_); puts 'a!'; end
 => :===
2.3.3 :004 > def b.===(_); puts 'b!'; end
 => :===
2.3.3 :005 > case a
2.3.3 :006?>   when b then nil
2.3.3 :007?>   end
b!
 => nil
```

**Comment by flash-gordon** [comment]
resolved with https://github.com/rom-rb/rom-sql/commit/da13da05f1df79ce198ed85e7b7caf7f641c39c0
