### ISSUE TITLE
Plans for the new mysql json column

### ISSUE THREAD

**Issue by alexandru-calinoiu** [rom-rb/rom-sql#175]
There is this new feature from mysql https://dev.mysql.com/doc/refman/5.7/en/json.html, are there any plans for it's support?

**Comment by flash-gordon** [comment]
@alexandru-calinoiu do you whether Sequel already supports it?

**Comment by alexandru-calinoiu** [comment]
Asked my question on their support forum There is this new feature from mysql https://dev.mysql.com/doc/refman/5.7/en/json.html, are there any plans for it's support?

**Comment by alexandru-calinoiu** [comment]
There is support now via an extension https://github.com/munshkr/sequel-mysql_json, can this be used in rom?

**Comment by solnic** [comment]
> There is support now via an extension https://github.com/munshkr/sequel-mysql_json, can this be used in rom?

Yes, but as long as it's not in the sequel gem, we shouldn't support it directly in rom-sql, and instead a plugin can be provided via external gem, ie `rom-mysql-json` or something.
