### ISSUE TITLE
Qualify columns in the WHERE clause

### ISSUE THREAD

**Issue by flash-gordon** [rom-rb/rom-sql#180]
At least things like `auto_restrictions` and `by_pk` views must apply qualified conditions otherwise using them leads to errors like `ambiguous column name: id` in the presence of joins.

**Comment by solnic** [comment]
It's been on my todo list. I wonder if it'd make sense to *always use attributes* instead of symbols. So even if you do `where(foo: "bar")` we'd translate this to `where(self[:foo].is("bar"))` as this way we will maintain properties like qualification.

**Comment by solnic** [comment]
Since we qualify by default starting from 2.0.0 this can be closed.
