### ISSUE TITLE
Applying a custom mapper to wrap_parent

### ISSUE THREAD

**Issue by mrship** [rom-rb/rom-sql#185]
Our data often requires a custom mapper to ensure sensible names for domain entity attributes, rather than the columns in the database. 

We have a use case where we want to pull back nested data that includes a parent entity that needs a custom mapper. I see that you can do this with `aggregate` but not with `wrap_parent` - is this something that can be supported?

**Comment by solnic** [comment]
It will be supported in rom 4.0. We need a better abstraction first.

**Comment by solnic** [comment]
It turns out to be trickier than I thought. For now please use combine/aggregate, if you have a really good reason to use `wrap`, please start a discussion on discourse.rom-rb.org and maybe we'll add support for this in rom 4.x
