### ISSUE TITLE
Negation attribute does not work

### ISSUE THREAD

**Issue by alexandru-calinoiu** [rom-rb/rom-sql#190]
Give I have a very simple schema with a column `status` as string.

The following query does not seem to produce the required result:

```
where((!status.is('running')) || (status.is(nil))
```

The result  is a `WHERE ... AND 0`

Expected result is `WHERE ... AND status != 'running' OR status IS NULL`

**Comment by AMHOL** [comment]
Hmm, perhaps we're just missing a `#not` method.

**Comment by solnic** [comment]
This is done in master. It'll be available in 1.3.0.
