### ISSUE TITLE
Cannot use the `by_pk` view when the PK is not present in the schema

### ISSUE THREAD

**Issue by flash-gordon** [rom-rb/rom-sql#192]
If we do not project the PK, `by_pk` fails with `KeyError`:
```ruby
rom.relation(:users).select(:name).by_pk(1).one
KeyError: :id attribute doesn't exist in users schema
```
It's easy to fix this for one-column PKs through passing the attribute via closure (like we do in `auto_restrictions`). For composite PKs we either need to use closures or come up with something else. I.e. we can have `base_relation.schema`, however this looks like an overkill.

**Comment by solnic** [comment]
well, I fixed it and broke everything else at the same time 🙈

**Comment by flash-gordon** [comment]
Oh, I forgot we have class-level schema lol. On the other hand it's not a bad thing to forget.

**Comment by solnic** [comment]
@flash-gordon yeah but it sucks that we access it via `self.class.schema` because this is the canonical schema and we should have a nice method to access it on `Relation` objects
