### ISSUE TITLE
Infer DB type in CAST

### ISSUE THREAD

**Issue by flash-gordon** [rom-rb/rom-sql#202]
We could infer database type based on attribute's ROM type when calling the `CAST` expression:

```ruby
# now
int::cast(string_column, :integer).as(:int_value)

# could be
int::cast(string_column).as(:int_value)
```

The problem is that this ROM type <-> DB type mapping actually depends on the used database. For instance, Oracle uses `VARCHAR2` for strings rather than `VARCHAR` (the latter does exist but has been deprecated for ages). I would be great to infer DB type for PG and MySQL at least.

See https://github.com/rom-rb/rom-sql/pull/201 for more info on this

**Comment by flash-gordon** [comment]
```
-      def cast(expr, db_type)
+      def cast(expr, db_type = TypeSerializer[:default].call(type))
         Attribute[type].meta(sql_expr: ::Sequel.cast(expr, db_type))
       end
 ```
@GustavoCaso somthing like this^ should work good enough

**Comment by GustavoCaso** [comment]
Great @flash-gordon Thanks I will create a PR with it
