### ISSUE TITLE
[inferrer] Support for PG range types

### ISSUE THREAD

**Issue by flash-gordon** [rom-rb/rom-sql#234]
I personally haven't had a chance to work with range types so one should read the docs before working on this issue: https://www.postgresql.org/docs/current/static/rangetypes.html 😄

**Comment by solnic** [comment]
I did. I even took a stab at adding support for them to rom-sql but gave up because it wasn't a half-an-hour-task :)

**Comment by solnic** [comment]
Done via #245 🎉
