### ISSUE TITLE
Warning Sequel::Postgres::PGArray::EMPTY_BRACKET

### ISSUE THREAD

**Issue by AlexanderMint** [rom-rb/rom-sql#239]
Ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

> .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rom-sql-1.3.3/lib/rom/sql/extensions/postgres/inferrer.rb:37: warning: constant Sequel::Postgres::PGArray::EMPTY_BRACKET is deprecated

Please correct the warning

**Comment by flash-gordon** [comment]
This was fixed in master (including 2.0.0 beta releases), for the v1.x branch you can pin Sequel to the version that doesn't issue the warning

**Comment by flash-gordon** [comment]
@AlexanderMint FYI 1.3.4 fixed the warning https://github.com/rom-rb/rom-sql/blob/release-1.0/CHANGELOG.md#v134-2017-09-12
