### ISSUE TITLE
Sequel 5 RuntimeError

### ISSUE THREAD

**Issue by mrpeterpeter** [rom-rb/rom-sql#240]
[This commit](https://github.com/jeremyevans/sequel/commit/c0ffcafb852240a94c460578333c029f5b100930) in Sequel version 5 changes `Sequel::SQL::Expression.to_s_method` by freezing `@comparison_attrs` and causing a RuntimeError with the message "can't modify frozen Array" when using the master branch.

**Comment by solnic** [comment]
@mrpeterpeter pls attach a backtrace, it's hard to say why this is happening

**Comment by mrpeterpeter** [comment]
Hi @solnic 

A big thank you to you and the rest of the team for ROM; hope I'm not wasting your time with an error on my part but I was getting this:

```ruby

cwd = File.expand_path(File.dirname(__FILE__))
$LOAD_PATH.unshift(cwd)

require 'rubygems'
require 'bundler/setup'
require 'rom-sql' 

configuration = ROM::Configuration.new(
  default: [:sql, 'postgres://localhost/test'],
) 

class Things < ROM::Relation[:sql] 
  schema(:things, infer: true)
end

configuration.register_relation(Things)
container = ROM.container(configuration)
things = container.relations[:things].to_a

# =>  
# ~> /usr/local/opt/rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/sequel-5.0.0/lib/sequel/sql.rb:78:in `concat': can't modify frozen Array (RuntimeError)
# ~>  from /usr/local/opt/rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/sequel-5.0.0/lib/sequel/sql.rb:78:in `attr_reader'
# ~>  from /usr/local/opt/rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/sequel-5.0.0/lib/sequel/sql.rb:190:in `<class:ComplexExpression>'
# ~>  from /usr/local/opt/rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/sequel-5.0.0/lib/sequel/sql.rb:137:in `<module:SQL>'
# ~>  from /usr/local/opt/rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/sequel-5.0.0/lib/sequel/sql.rb:62:in `<module:Sequel>'
# ~>  from /usr/local/opt/rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/sequel-5.0.0/lib/sequel/sql.rb:3:in `<top (required)>'
# ~>  from /usr/local/opt/rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/rom-sql-16b1a702a873/lib/rom/sql/types.rb:2:in `require'
# ~>  from /usr/local/opt/rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/rom-sql-16b1a702a873/lib/rom/sql/types.rb:2:in `<top (required)>'
# ~>  from /usr/local/opt/rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/rom-sql-16b1a702a873/lib/rom/sql/relation.rb:1:in `require'
# ~>  from /usr/local/opt/rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/rom-sql-16b1a702a873/lib/rom/sql/relation.rb:1:in `<top (required)>'
# ~>  from /usr/local/opt/rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/rom-sql-16b1a702a873/lib/rom/sql.rb:11:in `require'
# ~>  from /usr/local/opt/rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/rom-sql-16b1a702a873/lib/rom/sql.rb:11:in `<top (required)>'
# ~>  from /usr/local/opt/rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/rom-sql-16b1a702a873/lib/rom-sql.rb:1:in `require'
# ~>  from /usr/local/opt/rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/rom-sql-16b1a702a873/lib/rom-sql.rb:1:in `<top (required)>'
# ~>  from -:8:in `require'
# ~>  from -:8:in `<main>'

```

Removing the call to freeze in `Sequel::SQL::Expression.to_s_method` allows my apps to boot.

**Comment by flash-gordon** [comment]
I saw this issue when I was migrating my app to Sequel 5. In my case, it occurred when I had two `bundle/vendor` paths and Sequel got loaded from two different places, so I guess you should check if your problem is related. I'd start with checking the output of `$LOAD_PATH.grep(/sequel/)`

**Comment by mrpeterpeter** [comment]
Hi @flash-gordon 

I have used `sequel_pg` in some apps so I went back and checked again with the following minimal Gemfile:

```ruby
source 'https://rubygems.org'

git 'rom-rb:rom' do
  gem 'rom-core'
end

gem 'rom-sql',   git: 'rom-rb:rom-sql'
gem 'dry-logic', git: 'dry-rb:dry-logic'
gem 'dry-types', git: 'dry-rb:dry-types'
gem 'dry-struct'
gem 'pg'
```

My previous code will show the following if I comment out the call to `freeze`:

```ruby
$LOAD_PATH.grep(/sequel/) # => ["/usr/local/opt/rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/sequel-5.0.0/lib"]
```

But if leave `Sequel::SQL::Expression.to_s_method` unchanged the example crashes.

**Comment by flash-gordon** [comment]
@mrpeterpeter I can't reproduce this issue, I grabbed your gemfile and the example, they work fine for me. This must be somehow related to the fact that Sequel started to use `require_relative` to load its files. In my case, the problem was caused by the misconfigured environment. I'm not sure what causes the error in your case, I have to reproduce it first.

**Comment by mrpeterpeter** [comment]
@flash-gordon I can't seem to avoid this even with a fresh ruby env. I agree with you but I'm not sure how to correct it. 'sequel/core' loads 'sequel/sql' with `require_relative` as you say, so in 'rom/sql/types' `require 'sequel/sql'` seems to be the cause and not necessary.

**Comment by mrpeterpeter** [comment]
Opened [pull request](https://github.com/rom-rb/rom-sql/pull/248)

**Comment by flash-gordon** [comment]
@mrpeterpeter I’m not against removing that require but exists on purpose of making code dependencies clearer to see. However, before doing this I’d like to understand why the error happens in the first place because this may indicate a problem in Sequel, Bundler, or rbenv rather than in rom-sql itself. Do you have ideas how I can reproduce it?

**Comment by mrpeterpeter** [comment]
@flash-gordon and @solnic, I am glad to say I have managed to narrow the runtime error down to [Rbenv](https://github.com/rbenv/rbenv) version 1.1.0. I haven't worked out what was causing it, but it is fixed in the latest release [v1.1.1](https://github.com/rbenv/rbenv/tree/v1.1.1).

**Comment by flash-gordon** [comment]
@mrpeterpeter oh, good to know, thank you!

**Comment by mrpeterpeter** [comment]
FWIW after running bundle update to upgrade to the final release of 2.0.0 this problem reappeared! So actually my fix was the fresh ruby and gems and not a new version of rbenv. Still can't see what is causing this but if this catches you out the sledgehammer approach is to blow away your ruby environment.

**Comment by solnic** [comment]
@mrpeterpeter try w/o rbenv maybe?

**Comment by mrpeterpeter** [comment]
@solnic I had changed every variable before laying blame at rbenv; it's all good without it. Rbenv users beware ;p

**Comment by solnic** [comment]
I recommend switching to ruby-install + chruby

**Comment by paradisaeidae** [comment]
I compile ruby and use a (modified) chruby script. So I suggest the issue is in some area of double-loading, as I'm getting a lot of ' warning: already initialized constant Sequel::SQL::OrderedExpression....' messages.

**Comment by soylent** [comment]
In my case this issue happened because `sequel/sql` was loaded twice
1. the first time in `sequel/core`

```ruby
 require_relative "sql"
```

2. and the second time in `rom/sql/types`:

```ruby
require 'sequel/sql'
```

When `sequel/sql` is loaded the second time, something like this happens:
`Sequel::SQL::Expression.attr_reader([].freeze)` ->
`[].freeze.concat [:comparison_attrs]` ->
RuntimeError: can't modify frozen Array

The reason why `sequel/sql` is loaded twice is because `require` and `require_relative` behave differently: `require_relative` uses real path without symlinks and `require` does not. If you install rbenv or asdf via Homebrew then everything is stored in `/usr/local/Cellar/x/1.2.3` and symlinked to `/usr/local/opt/x`, which explains this issue.

This bug has been fixed in Ruby recently, please see https://bugs.ruby-lang.org/issues/10222

**Comment by flash-gordon** [comment]
@soylent thank you for letting us know! ❤️
