### ISSUE TITLE
Support for functions with `Any` return type

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-sql#270]
Since we have `Types::Any` now, we can add support for defining functions w/o return type, in which case `Types::Any` will be set by default, ie:

``` ruby
select { fun(:count, :id).as(:count), concat(:first_name, :last_name).as(:full_name) }
```

Refs rom-rb/rom-rb.org#227

**Comment by GustavoCaso** [comment]
I would love to help with this one
