### ISSUE TITLE
Add Relation#as_hash

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-sql#272]
Sequel has a sweet feature where you can ask for a hash by providing an attribute name. We could expose it too, with a small improvement that it doesn't require an argument, and we default to the pk attribute so:

``` ruby
pages.select(:id, :title).to_hash
=> {{1=>{:id=>1, :title=>"Page 1"}, 2=>{:id=>2, :title=>"Page 2"}}

pages.select(:id, :title).to_hash(:title)
=> {{"Page 1"=>{:id=>1, :title=>"Page 1"}, "Page 2"=>{:id=>2, :title=>"Page 2"}}
```

**Comment by flash-gordon** [comment]
Since `to_hash` is used by Ruby for implicit coercion I'd suggest using a different name. FWIW, `as_hash` looks good enough to me
See https://github.com/jeremyevans/sequel/issues/1375 and https://github.com/jeremyevans/sequel/commit/7f38429e43a8bd0eb5f013a742df867b4327a143

**Comment by timriley** [comment]
Wouldn't `#to_h` work, as the _explicit_ equivalent of `#to_hash`?

**Comment by flash-gordon** [comment]
@timriley it would but it's already implemented in `Enumerable` and behaves differently: https://ruby-doc.org/core-2.2.0/Enumerable.html#method-i-to_h

**Comment by timriley** [comment]
@flash-gordon ah, `#as_hash` it may have to be then :)

**Comment by abrthel** [comment]
Considering `#as_hash` is what sequel uses, it's for the probably best.

**Comment by GustavoCaso** [comment]
I would like to help with this one, if no one is already working on it

**Comment by solnic** [comment]
Right. Let's go with `as_hash`. @GustavoCaso it's yours now ;)
