### ISSUE TITLE
Support for subqueries in relations?

### ISSUE THREAD

**Issue by FilipVozar** [rom-rb/rom-sql#278]
Hi, first of all thank you for the amazing work, I've been experiencing with rom-rb (and dry-rb for that matter) and I really like it. It has a steeper learning curve, but it all starts coming together after a while of playing with it.

The task I've been struggling with is using a subquery in relations. Let me explain my use case (I'm using Postgres).

``` sql
CREATE TABLE entities (
  id serial primary key,
  name varchar(32)
)

CREATE TABLE results (
  id serial primary key,
  score numeric,
  entity_id int references entities(id)
)
```

One entity can have 0 or more results, but we're usually interested only in the most recent one (the one with the highest `id` for a given `entity_id`). I can get only the latest result for each entity with a query like this:

``` sql
SELECT DISTINCT ON(entity_id) * FROM results ORDER BY entity_id, id DESC;
```

Now I'd like to display entities ordered by score from their latest result (ignoring the ones that don't have any results). I can achieve that with a query like this, for example:

``` sql
SELECT entities.id, entities.name, latest_results.score
FROM (SELECT DISTINCT ON(entity_id) entity_id, score FROM results ORDER BY entity_id, id DESC) AS latest_results
INNER JOIN entities ON entities.id = latest_results.entity_id
ORDER BY lateset_results.score DESC;
```

I've tried to write a query like this using ROM relations, but no luck so far. My current solution is to create a view from the subquery in postgres, and join that view in relations. That works fine, but I dislike the idea of creating  a separate view for each subquery like this.

**Comment by FilipVozar** [comment]
update: I've been able to solve this using Sequel datasets directly - not sure if that's the right approach, but the idea is like this:
```ruby
class Entities < ROM::Relation[:sql]
  def with_results
    sub = results.dataset.select(:score).where(entity_id: Sequel.qualify(:entities, :id).order(:id).reverse.limit(1)
    new_dataset = entities.dataset.select_all.select_append {[Sequel.as(sub, :score]}.from_self(alias: :entities).where {score !~ nil}
    new(new_dataset)
  end
end
```

which produces a query like this one (according to PG query planner, this should be faster than join query in the original post)
```sql
SELECT * FROM (
  SELECT *, (SELECT score FROM results WHERE entity_id = entities.id ORDER BY id DESC LIMIT 1) as score
) AS entities WHERE score IS NOT NULL;
```

**Comment by solnic** [comment]
We're planning to add sub-query support soon. You can continue using Sequel's datasets for now, but eventually relations will support it.

**Comment by cutalion** [comment]
@solnic @flash-gordon how's the progress on this?

**Comment by cutalion** [comment]
Oh. I see it in changelog.
https://github.com/rom-rb/rom-sql/blob/master/CHANGELOG.md#v250-2018-06-08

**Comment by flash-gordon** [comment]
Added in https://github.com/rom-rb/rom-sql/pull/290

**Comment by wuarmin** [comment]
@cutalion Do we have a `from_self`-equivalent? I believe we can use subqueries in select and where-clause, but not as derived table. Am I right?
