### ISSUE TITLE
[Question] Support for Single and Class Table Inheritance

### ISSUE THREAD

**Issue by stefanrendevski** [rom-rb/rom-sql#313]
I am looking into this library as a replacement for ActiveRecord. I noticed that it uses Sequel underneath, so I was wondering if Sequel plugins for single/class table inheritance can be used with ROM? If not, how would one implement these features with this gem?

I realize STI can be trivial to implement with ROM mappers and a `type` column, but I don't see a clear way for implementing CTI, except auto-building the associations from within the relevant changesets. Does anyone have any pointers?

**Comment by solnic** [comment]
Please see [my reply](https://discourse.rom-rb.org/t/model-inheritance/82) on our forum, feel free to ask further questions there. We use issues for bug-reports only, so I'm closing this one.
