### ISSUE TITLE
Auto registering relations makes migrations impossible?

### ISSUE THREAD

**Issue by MiralDesai** [rom-rb/rom-sql#319]
**Describe the bug**

I feel like this is a bug, to run the `rake db:migrate` rake task, you need to setup a ROM container, but this automatically registers all your relations. An error is thrown telling me that a relation does not exist for a migration I have created, but now cannot run. This can be overcome by migrating the db first, then creating the relation and all related logic, but that seems like extra overheard, in the real world I don't want to deploy a migration to production, then do another deploy with my logic, I should be able to do it all in one go. It feels a bit backwards to me.

**To Reproduce**

1. run `rake db:create_migration[create_users]`
2. Create relation class and repository class if required. Implement logic for new table.
3. Attempt to run migration via `rake db:migrate`
4. `PG::UndefinedTable: ERROR:  relation "users" does not exist` error thrown as it attempts to register the `:users` relation before running the migration.

**Expected behavior**

After step 3 above, the container should recognise there is a pending migration and run it before attempting to register any relations.

I guess the main issue seems to be that ROM doesn't have any idea of which migrations have run? After deleting the relation classes associated to the new migration it still complained to me about a duplicate table, because it was trying to execute a previous migration that had already run? That doesn't seem right at all.

**Your environment**

- Affects my production application: **YES**
- Ruby version: 2.6.1
- OS: Mac OS 10.14 (Mojave)

This is happening in a simple Sinatra application where we are also using `dry-system` to load everything.

**Comment by solnic** [comment]
This is not a bug. For scripts/tasks that run migrations, you simply don't finalize container. You only need the db connection. Since you're using dry-system, you can put initial rom setup in an `init` step, and use that in `db:setup` task.

We should probably document this in user docs.

**Comment by MiralDesai** [comment]
Ok we're doing exactly that with dry-system so you led me down the right path. I was booting the entire system in my Rakefile instead of just requiring the `init` file for db:setup`. Silly mistake I suppose, but agree it would be good to have in the docs. I'll see if I can get a PR up for that on the other repo.
