### ISSUE TITLE
Attribute methods not available *within* a relation, but are *outside* of a relation

### ISSUE THREAD

**Issue by ianks** [rom-rb/rom-sql#385]
### Describe the bug

When attempting to use attribute methods within a `where` block inside of a relation, a `NoMethodError` is raised. The strange part is: things work perfectly fine in the when accessing the attribute *outside* of the relations.

```sh
[5]> ROM.env.relations[:store_inquiries][:flooring_interests].length
=> #<ROM::SQL::Attribute[Integer] name=nil sql_expr=#<Sequel::SQL::Function @name=>:array_length, @args=>[#<Sequel::Postgres::ArrayOp @value=>#<Sequel::SQL::QualifiedIdentifier @table=>:store_inquiries, @column=>:flooring_interests>>, 1], @opts=>{}> alias=nil>

[6]> self[:message].length
=> # NoMethodError: undefined method `length' for #<ROM::SQL::Attribute:0x00007fcb75ecdbd0>
```

### To Reproduce

```ruby
module Store
  class Inquiries < ROM::Relation[:sql]
    schema(:store_inquiries, infer: false) do
      attribute :flooring_interests, ROM::SQL::Postgres::Types::Array('text')
    end

    def broken
      where(self[:flooring_interests].length > 5)
      # also broken
      where { flooring_interests.length > 5 }
    end
  end
end
```

### Expected behavior

I would expect the attributes methods to be accessible *within* the relation as well as the *outside* the relation.

### Your environment

- **Affects my production application**: No
- **Ruby version**: 2.7.1
- **OS**: Mac OSX
- **rom-sql version**: 3.2.0

**Comment by ianks** [comment]
OK, so it seems like I found the issue. Setting `struct_namespace` makes this problem go away:

```ruby
module Store
  class Inquiries < ROM::Relation[:sql]
    struct_namespace ::Entities

    schema(:store_inquiries, infer: false) do
      attribute :flooring_interests, ROM::SQL::Postgres::Types::Array('text')
    end
  end
end
```

So this may not be a bug after all. Out of curiosity, why does it work this way?

**Comment by flash-gordon** [comment]
`.length` is a function call [defined on PG::Array type](https://github.com/rom-rb/rom-sql/blob/4740e2e961f0184f515269ed409f21b0180ac875/lib/rom/sql/extensions/postgres/types/array.rb#L133-L135). It works regardless of where it's called, I checked it. rom-sql doesn't translate arbitrary method_missing hits to function calls, that's why `self[:message].length` throws an error

**Comment by solnic** [comment]
@flash-gordon are you saying this is not a bug?

**Comment by flash-gordon** [comment]
@solnic yep
