### ISSUE TITLE
Improved query DSL

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-sql#48]
Currently we're using Sequel DSL to build queries (aka `relation views`), it's good-enough for now but I don't consider it to be the final solution and would be great to come up with a simpler DSL for 1.0.0.

Using rom relations means leveraging features of your database, we want to focus on building optimized queries that return results that match exactly what we want to have from the application domain point of view. This means using joins and projecting data in all kinds of ways is a typical usage of rom-sql, using mappers to further transform data should be a rare use-case.

This comes with a couple of challenges:
- Renaming columns
- Qualifying columns
- Extending header (aka columns)
- Selecting columns automatically based on the view definition
- Extracting values from a loaded relation that is passed into curried-for-combine-views

Here's a typical scenario that uses sequel naming conventions to qualify/rename columns and join relations:

``` ruby
class Tasks < ROM::Relation[:sql]
  # we define the header explicitly
  view(:for_users, [:id, :title, :user_id]) do |users|
    select(
      # even though we have the header defined, we still need to manually select
      # the columns, it's tricky because you can select columns and rename them using
      # various approaches
      :tasks__id, :tasks__title, :tasks__user_id
    ).inner_join(
      # qualifying column names is a good habit, it's easy to use wrong column name
      # accidentally and in some scenarios it will go unnoticed (and obviously cause major bugs)
      # the issue here is that underscore-based approach from sequel is ugly when names are long
      :users, users__id: :tasks__user_id
    ).where(
      # writing that `.map` on input relation is a super-common thing to do, this is a loaded relation
      # so we could introduce a plugin that extracts specific information from it
      #
      # ie we could have `users.foreign_keys` or `users.primary_keys`
      tasks__user_id: users.map { |u| u[:id] }
    )
  end
end
```
### Ideas for an improved DSL

????? TBD
##

**Comment by endash** [comment]
So at a minimum it makes sense to support nested hashes for specifying keys.

```ruby
class Tasks < ROM::Relation[:sql]
  # we define the header explicitly
  view(:for_users, [:id, :title, :user_id]) do |users|
    select(tasks: [:id, :title, :user_id])
      .inner_join(:users, {users: :id, tasks: :user_id})
      .where(tasks: {user_id: users.map { |u| u[:id] }})
  end
end
```

**Comment by endash** [comment]
@solnic could you elaborate on/rephrase "Extracting values from a loaded relation that is passed into curried-for-combine-views"?

**Comment by solnic** [comment]
@endash sure, sorry for not being specific there. It's a very common pattern that a relation view receives a loaded relation to generate a query for relation composition. ie in rom-repo you can do `users.combine_children(many: tasks.for_users)` which results in materializing `users` and passing them to `tasks.for_users`. Them, typically, you do `where(users__id: users.map { |u| u[:id] })`. Since passed in `users` is `Relation::Loaded` rather than a plain array, we are free to introduce new interfaces to simplify this process.
