### ISSUE TITLE
Problems with UTF-8 encoding

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-sql#50]
It was reported on SO that when inserting non-ascii utf-8 chars the encoding gets messed up. More info [here](http://stackoverflow.com/questions/34207951/what-is-the-correct-way-to-use-utf-8-characters-with-postgresql-and-ruby-object)

**Comment by gotar** [comment]
Tested by few of use. Just works. Must be some user specific problem, not ROM related.
