### ISSUE TITLE
Unable to set path for migrations on a gateway

### ISSUE THREAD

**Issue by robjacoby** [rom-rb/rom-sql#52]
Currently, when running multiple SQL gateways, if all migrations are in the same path (`db/migrate`), they will all be run when calling `ROM::SQL::Gateway#run_migrations`.  The solution to this is to separate the migrations into separate directories (which also makes sense from a code perspective)

Unfortunately, due to the `ROM::SQL::Migration::Migrator` option being reader only, there is no way to override the default. See https://github.com/rom-rb/rom-sql/blob/master/lib/rom/sql/migration/migrator.rb#L10

My preference would be passing in an option when defining the gateway. Something like the following might work?

``` ruby
ROM::Configuration.new(
  default: [:sql, 'postgres://localhost/task_master', migration_path: 'db/migrate/default'], 
  legacy: [:sql, 'mysql2://localhost/tasks', migration_path: 'db/migrate/legacy']
)
```

**Comment by aarontc** [comment]
I ran into this issue myself - even with a single gateway there seems to be no way to specify a migration path.

**Comment by flash-gordon** [comment]
Now this should be possible in this way
```ruby
conn1 = Sequel.connect(uri1)
conn2 = Sequel.connect(uri2)
migrator1 = ROM::SQL::Migration::Migrator.new(conn1, path: migration1_dir)
migrator2 = ROM::SQL::Migration::Migrator.new(conn2, path: migration2_dir)
rom = ROM.container(
  default: [:sql, conn1, migrator: migrator1],
  non_default: [:sql, conn2, migrator: migrator2]
)

rom.gateways[:default].run_migrations # run migrations from migration1_dir
rom.gateways[:non_default].run_migrations # run migrations from migration2_dir
```

I haven't tested it, so lemme know if something doesn't work as expected. It's rather verbose but I believe we'll make it more concise during the work on migrations for rom-sql 2.0.
