### ISSUE TITLE
How to use with dry-data?

### ISSUE THREAD

**Issue by davispuh** [rom-rb/rom-sql#55]
I'm really lost on this because all documentation have been quite confusing as it explains individual parts but not how everything works together.

Basically I'm looking for some full example from table creation till data insertion.

So for example I've this

```ruby
class User < Dry::Data::Struct
  attribute :id, Types::Int
  attribute :name, Types::String
  attribute :email, Types::String
end

class Post < Dry::Data::Struct
  attribute :id, Types::Int
  attribute :user, User
  attribute :text, Types::String
end

```

and since I'm using ROM as abstraction it should be possible to easily reuse this for persistence (not recreate attributes again for ROM) and automatically create tables and easily insert data by passing instances of these.

**Comment by solnic** [comment]
This type of functionality is not done yet, hence there are no docs. I'm working on schema support for relations that will use dry-data API, from that we can infer things like automatic commands and schema migrations. I actually plan to provide auto-migration API too, like we had in DataMapper.

For now, please stay tuned, I'm doing my best to push this forward but I'm working on multiple projects simultaneously (rom-*, dry-* and rodakase...) so it's going pretty slow.
