### ISSUE TITLE
Ability to use with ActiveRecord's connection?

### ISSUE THREAD

**Issue by joevandyk** [rom-rb/rom-sql#56]
I'd like to look at using ROM in our codebase, but we would need to use the same database connection that ActiveRecord uses. Is that (or will that) be possible?

**Comment by hmadison** [comment]
You can use the same credentials that ActiveRecord would use, but not the same driver level connection object.

**Comment by solnic** [comment]
See if you can share connection between Sequel and AR - if it's possible, then it's also possible in ROM

**Comment by endash** [comment]
To further clarify, you can pass a Sequel::Database (resulting from Sequel.connect) to ROM rather than a set of connection details, so if you can do it with Sequel you can do it with ROM easily. Conversely, if you can't do it with Sequel then there's no change we can make to ROM to make it happen.
