### ISSUE TITLE
Support for native upserts in PG

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-sql#65]
It would be really great to have an upsert command that uses native features of PG

**Comment by gotar** [comment]
Will do it

**Comment by solnic** [comment]
Fantastic :) Let's start with some really basic functionality for PG first and take it from there

**Comment by gotar** [comment]
https://github.com/rom-rb/rom-sql/pull/66

**Comment by flash-gordon** [comment]
was added to rom-sql v0.8.0
