### ISSUE TITLE
Clarify schema syntax for defining associations 

### ISSUE THREAD

**Issue by daniels** [rom-rb/rom-sql#67]
If a relation is registered under a different name than the underlying dataset, it is not obvious what name goes where when defining associations.

```ruby
config.relation(:users) do
  dataset :user

  schema(:user) do                                         # <= dataset name
    attribute :user_id, ROM::SQL::Types::Serial
    attribute :name, ROM::SQL::Types::String

    associate do
      many :tasks                                          # <= relation name
    end
  end
end

config.relation(:tasks) do
  dataset :task

  schema(:task) do                                         # <= dataset name
    attribute :task_id, ROM::SQL::Types::Serial
    attribute :user_id, ROM::SQL::Types::ForeignKey(:user) # <= dataset name
    attribute :name, ROM::SQL::Types::String

    associate do
      one :users                                           # <= relation name
    end
  end

  def for_users(users)
    where(user_id: users.map { |user| user[:user_id] })
  end
end
```

When mixing these up and using them (through `ROM::Repository#aggregate`) you get `NoMethodError` on `nil:NilClass`, where the missing method is `foreign_key` if you used relation name in `ROM::SQL::Types::ForeignKey()` and `primary_key` if you used dataset name in the `associate` block.

I'm not sure what the best solution would be here – changing the behavior or just emphasis the current behavior in the documentation. Or maybe it would help if the error was raised when the relation/dataset couldn't be found rather than when calling a method on the missing object.

**Comment by flash-gordon** [comment]
OK, now we can say that we _always_ use database names. This means if you want to associate a relation with a name different than the underlying table name you go with
```ruby
associate do
  many :my_table_name, relation: :my_relation_name
end
```
Also you can provide an optional association name that can be used later in rom-repo
```ruby
schema(:posts) do
  attribute :author_id, ROM::SQL::Types::ForeignKey(:users) 

  associate do
    belongs :users, relation: :people, as: :owner
  end
end
###
people_repo.posts.combine(:owner).one.owner
```
