### ISSUE TITLE
Plugin for generating common relations

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-sql#69]
How about adding a plugin that would generate relation views restricted by PK + any indexed column?

So ie:

``` ruby
class Users < ROM::Relation[:sql]
  schema do
    attribute :id, Types::Serial
    attribute :name, Types::Index(:int) # we don't have that yet btw
  end
end

# this would be generated automatically:
users.by_id
users.by_name
```

It's a common pattern so a bit of Convention-Over-Configuration here would be helpful.
##

**Comment by hmadison** [comment]
Would we only want this on indexed columns?

**Comment by solnic** [comment]
Yes, the purpose of this feature would be to have common restrictions by default for common queries and update/delete commands

**Comment by timriley** [comment]
Yes! Seems like a smart way to reduce boilerplate. We'd use it. And the plugin would mean it's opt-in anyway, right?

**Comment by solnic** [comment]
Yes, I would probably have it disabled by default to keep the core behavior small. In plenty of relations you will simply not need it.

**Comment by timriley** [comment]
Sounds good to me, then.

**Comment by flash-gordon** [comment]
I should admit that foreign keys _should_ be indexed in the most of cases so perhaps we need to generate views for them as well, wdyt?

**Comment by solnic** [comment]
@flash-gordon yeah anything that's indexed, because you typically use indices for columns used by restrictions :)
