### ISSUE TITLE
Possible to specify default sort key?

### ISSUE THREAD

**Issue by billdueber** [rom-rb/rom-sql#76]
I have a legacy table with no `id` column, and keep getting errors because it was attempting to `order by tablename.id`

**Comment by flash-gordon** [comment]
Interesting, does your table have a primary key constraint at all? 
You can override the default dataset with arbitrary ordering like this
```ruby
dataset { select(*columns).order(:your_table__any_column_you_like) }
```
Syntax `:table_name__column` is what underlying Sequel gem uses for qualified names.

**Comment by billdueber** [comment]
It does have a unique pk -- it just doesn't happen to have a column called `id`. Is there a reason a sort order is automatically put into the dataset definition? If there is, then it should probably have its column (columns and direction?) configurable

**Comment by flash-gordon** [comment]
@billdueber rom-sql tries to obtain a primary key name from the database via Sequel's API. As of version 2.0, we recommend use schemas (http://rom-rb.org/learn/sql/schemas/) where you can mark a column (or columns) as a primary key. I'm curious why Sequel failed to detect your PK name automatically, could you provide table's DDL and say what database are you working with, please? One reason I'm thinking of is a presence of a unique index but a lack of a primary key mark.

**Comment by solnic** [comment]
I'm closing this one since there was no reply for 2 months. Please re-open if needed.
