### ISSUE TITLE
.qualified does not work with Sequel expressions

### ISSUE THREAD

**Issue by janjiss** [rom-rb/rom-sql#83]
Hey folks, stumbled on following situation. If I want to have qualified columns and have Sequel expression in them, it fails to parse it and just tries to do .to_s on Sequel expression: 

```
metas.select(
  :id,
  Sequel.expr(:meta).pg_jsonb.get_text("name").as(:name)
).qualified
.left_join(
  :accounts, accounts__name:   Sequel.expr(:meta).pg_jsonb.get_text("name")
).to_a
```

It returns following error

```
Sequel::DatabaseError: PG::UndefinedColumn: ERROR:  column metas.#<Sequel::SQL::AliasedExpression:0x007fa0558303b8> does not exist
LINE 1: SELECT "metas"."id", "metas"."#<Sequ...

from /Users/janjiss/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sequel-4.37.0/lib/sequel/adapters/postgres.rb:187:in `async_exec'
```
##

**Comment by janjiss** [comment]
Looks like `Sequel.expr(:meta).pg_jsonb.get_text("name")` returns `Sequel::SQL::AliasedExpression`. Any ideas how to convert this to sql literal? And another problem is that `Sequel.expr(:meta)` is a `Sequel::SQL::Identifier`. Essentially there are objects inside other objects. I want to figure out how to convert these objects to something we can use. Any ideas?

**Comment by solnic** [comment]
Actually, we need to create our own API for this types of objects. There should be no need to refer to sequel directly when using rom-sql.

**Comment by janjiss** [comment]
What I can think of, that would could solve this problem in the most easy possible way is to allow callable objects to be passed:
```
def qualified
  self.class.new(columns.map { |col| col.respond_to?(:call) ? col.call : :"#{table}__#{col}" }, table)
end
```
Thoughts?

**Comment by solnic** [comment]
I made a ton of improvements in rom-sql so starting with 1.0.0 you'll be able to do this:

``` ruby
metas.
  select { [id.qualified, meta.pg_jsonb.get_text("name").as(:name)] }.
  left_join(:accounts, accounts[:name].qualified => metas[:meta].pg_jsonb.get_text("name")
```
