### ISSUE TITLE
Inferred types are over-strict

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom-sql#88]
Adding `schema(:db, infer:true)` to an existing relation, and I get the following errors:

``` 
     Dry::Types::ConstraintError:
       Sun, 11 Sep 2016 08:50:45 -0400 violates constraints (type?(Time) failed)
```

the column itself is a standard postgres timestamp:

```
 created_at   | timestamp without time zone | 
```

**Comment by solnic** [comment]
@flash-gordon wdyt about using non-strict types by default? and maybe adding a `strict: true` option to the inferrer?

Regardless of this, I wonder what the actual type is, since `type?(Time)` failed then...what the hell is it? :D

**Comment by flash-gordon** [comment]
@solnic it's not a bad idea to make it configurable, but what kind of types are you suggesting instead? Coercible? This is doable, no doubt, but I'm not sure if this will help in this particular case, depends on what @cflipse is trying to insert/update

**Comment by cflipse** [comment]
It's coming in from a rom-model form with `timestamps` set on input ...  so ... DateTime.

**Comment by flash-gordon** [comment]
Aha! So, dry-t doesn't have a coercible time type, this means it can't transform DateTime to Time ootb. Should we do something about it, @solnic?

**Comment by jodosha** [comment]
I agree on this. Schema hash should be more relaxed. 👍 

For instance:

```ruby
UserRepository.new.create(name: 'L', active: nil)
  # => raises "nil violates constraints (type?(FalseClass) failed)"
```

(I'm using `relation.schema_hash` to do data transformations)

**Comment by solnic** [comment]
Yeah I agree, this shouldn't be strict by default when inferring

**Comment by solnic** [comment]
@flash-gordon just plain definitions ie `Types::String` etc.

**Comment by jodosha** [comment]
In my branch I tried with `Maybe::Optional`. First of all `Bool`, `Date` and `Time` aren't defined under that module. Is that intentional?

I defined them, but `Maybe` types replace `nil` with `None`, which causes an error in Sequel cause it can't represent `None` as a SQL literal.

**Comment by solnic** [comment]
@jodosha *don't* use maybes for this, it is not worth the effort and adds additional overhead :)

**Comment by jodosha** [comment]
Fine :)

Should Coercible be enough?

**Comment by flash-gordon** [comment]
@solnic plain definitions will ignore actual values IIRC. But what about special PG types, should be values coerced to custom Sequel's types or not?

**Comment by solnic** [comment]
For coercions things stay the same. This is how I've using it (as in with
explicit defs)

**Comment by jodosha** [comment]
@solnic @flash-gordon @cflipse I made a PR to fix this problem 😉
