### ISSUE TITLE
Should allow String substitutes

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom-sql#89]
I have a value object that stands in for a string, with some stricter formatting rules.  This class defines `to_str` and `sql_literal(ds)`  and can stand in for a string when writing to the database.  I can use `String(value)` to cast to a pure string.

With a schema,  both inferred, and when defined as `Types::Coerced::String`, I get an error when using an attribute of this class.  

Types, strict or not, should probably make a reasonable effort to attempt to use the implicit conversion methods

**Comment by solnic** [comment]
Hmm, this works for me:

``` ruby
require 'rom-sql'
require 'rom-repository'

class Users < ROM::Relation[:sql]
  schema(:users) do
    attribute :id, Types::Serial
    attribute :name, Types::String
    attribute :type, Types::Coercible::String
  end
end

class Type < Struct.new(:value)
  def to_str
    value
  end
end

class UserRepo < ROM::Repository[:users]
  commands :create
end

config = ROM::Configuration.new(:sql, 'sqlite::memory')
config.register_relation Users

config.gateways[:default].connection.create_table(:users) do
  primary_key :id
  column :name, String
  column :type, String
end

container = ROM.container(config)
user_repo = UserRepo.new(container)

john = user_repo.create(name: 'John', type: Type.new('User'))

puts john.inspect
# #<ROM::Struct[User] id=1 name="John" type="User">
```

I suspect this only fails when we use inference, as we have strict types by default. We can change them to non-strict, or coercible by default.

**Comment by solnic** [comment]
v0.9.0 was released and it should work there
