### ISSUE TITLE
Infer Postgres column types in relation schemas

### ISSUE THREAD

**Issue by timriley** [rom-rb/rom-sql#90]
http://rom-rb.org/learn/sql/schemas/ talks about how you can use the special postgres column types in schemas, declaring the attributes like this:

```ruby
class Users < ROM::Relation[:sql]
  schema do
    attribute :meta, Types::PG::JSON
    attribute :tags, Types::PG::Array
    attribute :info, Types::PG::Hash
  end
end
```

But it'd be great if `schema(:foo, infer: true)` would detect and use these types. Right now, it fails with an error like this:

```
KeyError: key not found: :json
/Users/tim/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rom-sql-0.8.0/lib/rom/sql/schema/inferrer.rb:52:in `fetch'
/Users/tim/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rom-sql-0.8.0/lib/rom/sql/schema/inferrer.rb:52:in `build_type'
```

Looking at the source file, this'd be because there's no type_mapping entry for a `json` column.

The benefit of being able to infer these would be that you don't have to manually declare your entire table's schema as soon as you go ahead and add just one special postgres column.

**Comment by jodosha** [comment]
@timriley Please have a look at https://github.com/rom-rb/rom-sql/pull/84 😉

**Comment by timriley** [comment]
Oh! Wonderful stuff, @jodosha 😄
