### ISSUE TITLE
Cannot have colon (':') in password for mysql

### ISSUE THREAD

**Issue by flash-gordon** [rom-rb/rom-sql#92]
Original issue: https://github.com/rom-rb/rom/issues/355
@alderion commented an hour ago
the below does not work. results in access denied.
```ruby
ROM.container(:sql, "mysql://usr:pass:word@machine/database") do |rom| ...
ROM.container(:sql, "mysql://usr:pass:word@machine/database") do |rom| ...
ROM.container(:sql, "mysql://usr:'pass\:word'@machine/database") do |rom| ...
```
am i doing it wrong or does rom not support a password that contains a colon?

**Comment by flash-gordon** [comment]
@alderion, it's a Sequel's behavior. Fortunately, you can use a hash instead of a string, like this:
```ruby
ROM.container(
  :sql, 
  adapter: 'mysql2', 
  user: 'usr', 
  password: 'pass:word', 
  database: 'database', 
  host: 'machine'
)
```

Please, try it and close the issue if it works for you

**Comment by alderion** [comment]
thanks so much!  sorry about cluttering up the issue queue.

**Comment by flash-gordon** [comment]
no worries, it's tricky a bit to make it right on the first attemp :)  Lemme know if this works, I didn't test it

**Comment by flash-gordon** [comment]
I tested it, `"mysql2://usr:pass:word@machine/database"` works fine as well, but you use  `mysql2` adapter, not just `mysql`. Closing this
