### ISSUE TITLE
How can we not infer relation attributes?

### ISSUE THREAD

**Issue by TiteiKo** [rom-rb/rom-sql#98]
I'm working on an existing database, on a 6 years old project, with a continuous deployment workflow.

Something I sometimes come across is removing columns from a table. We should be able to make 1 commit to remove all usage of the column, and then 1 commit to actually drop the database column, all without any errors or downtime.

If the attributes are inferred and the select queries specify all inferred columns, there will be (as there is with active record) database query errors when dropping the column.
Moreover, it requests data from de db that won't in any case be used.

ATM, I'm just playing around trying to get a grasp on ROM, and tried something like this:

```ruby
class Users < ROM::Relation[:sql]
  schema :users, infer: false do
    attribute :id, Types::Int.meta(primary_key: true)
    attribute :email, Types::String
  end
end
```

```
irb(main):003:0> rom.relation(:users)
=> #<ROM::Relation[Users] dataset=#<Sequel::Postgres::Dataset: "SELECT \"id\", \"login\", \"email\", [all the other existing fields] FROM \"users\" ORDER BY \"users\".\"id\"">>
```

Am I missing something?

**Comment by flash-gordon** [comment]
Right now schemas are used only for writing, ie for commands. But you can override an underlying dataset which keeps a list of columns for `SELECT`s with
```ruby
dataset do |relation|
  pk_header = klass.primary_key_header(db, table)
  select(*relation.schema.attributes.keys).order(*pk_header.qualified)
end
```
This _should_ work, but I didn't test it
You may find useful [the default dataset implementation](https://github.com/rom-rb/rom-sql/blob/a1ff939558d73fbee50d76d1faffce410a54ea3d/lib/rom/sql/relation.rb#L50-L59) and [ the bootstrapping code](https://github.com/rom-rb/rom/blob/179772b11bd39ceaae8da82c39a3bf4afd655e2b/lib/rom/setup/finalize/finalize_relations.rb#L47-L57)

**Comment by TiteiKo** [comment]
Thanks a lot!

Working snippet in case somebody else needs it someday:

```ruby
class Users < ROM::Relation[:sql]
  schema :users, infer: false do
    attribute :id, Types::Int.meta(primary_key: true)
    attribute :email, Types::String
  end

  dataset do |relation|
    pk_header = relation.primary_key_header(db, :users)
    select(*relation.schema.attributes.keys).order(*pk_header.qualified)
  end
end
```

```
irb(main):003:0> rom.relation(:users)
=> #<Users dataset=#<Sequel::Postgres::Dataset: "SELECT \"id\", \"email\" FROM \"users\" ORDER BY \"users\".\"id\"">>
```

**Comment by solnic** [comment]
I'd appreciate if somebody could report an issue about using schema attrs
for the default dataset. It's a simple thing to do I believe.
